Added grid3 capacity to the explorer grid statistics
threefoldtech/nodes-explorer pull request #13
Opened 2022-01-05 07:52 UTC by dmahmouali

![image](https://user-images.githubusercontent.com/36021484/148179879-a8fa32fe-a3f5-4ee0-a9cc-84f7a384a9fe.png)

issue: https://github.com/threefoldtech/nodes-explorer/issues/12

2022-01-05 08:01 UTC, DylanVerstraete requested changes
Besides 1 typo, you approached this solution in the wrong manner. 

When the user requests stats, the network can be (mainnet, testnet, devnet OR "all") 

Look at the implementation of `getItems` to see how the data is actually fetched. I would start to actually implement the solution there. If you need help or have any additional question, feel free to dm me.

2022-01-05 08:06 UTC, DylanVerstraete commented
Either you extend `getItems` or your make sure the stats handler for V3 can also handle network `all`

2022-01-05 18:57 UTC, xmonader commented on frontend/src/App.vue
> +          <div class="grid3labal">
label*

2022-01-05 18:57 UTC, xmonader commented on frontend/src/App.vue
> +.grid3labal {
label*

2022-01-06 14:32 UTC, DylanVerstraete requested changes

2022-01-06 14:32 UTC, DylanVerstraete commented on server/controllers/stats.js
> +      return c;
Write as 

`return results.map(r => r.data)`

2022-01-06 14:32 UTC, DylanVerstraete commented on server/controllers/stats.js
> +      return [];
Return a httpError

2022-01-06 14:32 UTC, DylanVerstraete commented on server/controllers/stats.js
> +    log.warn(error)
return httpError

2022-01-06 14:32 UTC, DylanVerstraete commented on server/controllers/stats.js
> +      return c;
remove ";"

2022-01-06 15:10 UTC, merged